### ISSUE TITLE
Can't add Core_kernel@v0.12.0 library to Revery UI

### ISSUE THREAD

**Issue by hexiangdong2017** [janestreet/core_kernel#91] opened 2019-04-09 14:04 UTC
I was using the GUI Library named Revery UI(https://github.com/revery-ui/revery/)
However, I can't add Core_kernel to it.
But when I change the version of Core_kernel from v0.12.0 to v0.11.1, it works.
So why Core_kernel@v0.12.0 can't add to Revery UI?
Follows are the log:
```
info esy build 0.5.6 (using package.json)
info building @opam/base@opam:v0.12.0@bd6e6655
error: build failed with exit code: 1
build log:
# esy-build-package: building: @opam/base@opam:v0.12.0
# esy-build-package: pwd: C:\Users\cloud.esy\3_\b\opam__s__base-opam__c__v0.12.0-0a378147
# esy-build-package: running: "dune" "build" "-p" "base" "-j" "4"
File "_build/default/src/mpopcnt.sexp", line 1, characters 1-11:
1 | '(-mpopcnt)'
^^^^^^^^^^
Error: too many s-expressions found in input
error: command failed: "dune" "build" "-p" "base" "-j" "4" (exited with 1)
esy-build-package: exiting with errors above...

building @opam/base@opam:v0.12.0
esy: exiting due to errors above
```

**Comment by hexiangdong2017** [comment] 2019-04-09 14:04
@seliopou @trefis @bmillwood @TyOverby

**Comment by hhugo** [comment] 2019-04-09 15:11
```
# esy-build-package: running: "dune" "build" "-p" "base" "-j" "4"
File "_build/default/src/mpopcnt.sexp", line 1, characters 1-11:
1 | '(-mpopcnt)'
```
This issue is with `base`, not with `core_kernel`.

**Comment by hhugo** [comment] 2019-04-09 15:12
related to https://github.com/janestreet/base/pull/60

**Comment by hexiangdong2017** [comment] 2019-04-10 04:31
So how can i solve the problem now? @hhugo

**Comment by hhugo** [comment] 2019-04-10 04:56
try `opam pin base https://github.com/janestreet/base.git#v0.12.0-for-win`. It this works for you, we could try to do an official minor release of base.

**Comment by hhugo** [comment] 2019-04-10 05:03
cc @xclerc

**Comment by hexiangdong2017** [comment] 2019-04-12 04:17
But I was using esy on Windows ,so I can't try opam pin base https://github.com/janestreet/base.git#v0.12.0-for-win
@hhugo

**Comment by hhugo** [comment] 2019-04-12 08:08
I don't know how esy works. I spent few minutes on `esy.sh` and found https://esy.sh/docs/en/using-repo-sources-workflow.html. You'll probably find help on  https://discuss.ocaml.org if you need.

**Comment by jordwalke** [comment] 2019-05-20 08:42
This is being fixed by @strid in [this pr](https://github.com/esy-ocaml/esy-opam-override/pull/43).

base was having trouble building on windows.

**Comment by hhugo** [comment] 2019-05-20 09:04
@xclerc, can we make a minor release for `base.v0.12` using https://github.com/janestreet/base/commits/v0.12.0-for-408 ?

**Comment by hhugo** [comment] 2019-05-20 09:55
@jordwalke, @hexiangdong2017, can someone confirm that the issue is resolved by using this branch
https://github.com/janestreet/base/tree/v0.12.0-for-win ?

**Comment by ulrikstrid** [comment] 2019-05-20 10:14
@hhugo I tried it on my machine and it builds

**Comment by xclerc** [comment] 2019-05-22 08:33
Sorry fot the delay; I just opened https://github.com/ocaml/opam-repository/pull/14171 with
a new version of Base including the fix mentioned by @hhugo.

**Comment by hhugo** [comment] 2019-05-28 06:40
base v0.12.1 has been release. It should fix the build on windows.

**Closed by hhugo** 2019-05-28 06:40 UTC
